spring:
  datasource:
    url: jdbc:mysql://localhost:3306/coursemanage?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&useLegacyDatetimeCode=false
    username: root
    password: zhang
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  jackson:
    time-zone: GMT+8
application:
  profile: D:/Profession/WorkSpace/Store/CourseManage/
server:
  port: 8181
